# Generated by Django 4.1.3 on 2022-11-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_image',
            field=models.ImageField(default='default.jpg', upload_to='bikes'),
        ),
    ]
